# This is a basic workflow to help you get started with Actions

name: Build and Deploy.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Build
      run: expo build:web
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - name: Copy files to the website with the AWS CLI
      run: |
        aws s3 sync ./web-build ${{ secrets.AWS_S3_BUCKET }}/games/crisps/
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
         # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465  
        # Optional (recommended): mail server username:
        username: ${{secrets.MAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
       # Required mail subject:
        subject: Github Actions - Pulbish and build of ${{github.repository}} completed sucsessfully!
      # Required recipients' addresses:
        to: ${{secrets.MAIL_USERNAME}}
      # Required sender full name (address can be skipped):
        from: headb
      # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true  
      # Optional plain body:
        body: Build and Publish job of ${{github.repository}} completed successfully!
